apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-1
  labels:
    app: ubuntu-1
  namespace: test-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-1
  strategy: {}
  template:
    metadata:
      labels:
        app: ubuntu-1
    spec:
      containers:
        - name: ubuntu-1
          image: ubuntu:latest
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
          resources:
            limits: 
              cpu: "1"
              memory: "128Mi"